### PR TITLE
Allow frame to be moved with arrow keys

### PR DESCRIPTION
**Pull request by cdeconinck**
Currently it work only with the frame hook by the lib but it would be nice to use the same logic for all the frame in edit mode

### CODE REVIEW

**Comment by teelolws** [comment]
Interesting idea, I'll check it out. Even Blizz's base Edit Mode doesn't do this. It won't be safe to spread this functionality into Blizzards frames, unfortunately. Can't risk the taint.

**Comment by teelolws** [comment]
Looks good! Haven't had any problems with this.

**Comment by teelolws** [comment]
You've made a few useful commits now. Whats your CurseForge username so I can give you proper credit?

**Comment by cdeconinck** [comment]
Oh thank you, i've just created my account on curse (@rashkay)

**Pull request merged**
