### PR TITLE
Add totem bar

### PR DESCRIPTION
**Pull request by cdeconinck**
Tested on live and beta

### CODE REVIEW

**Comment by teelolws** [comment]
Not a Shaman. Is that no longer the same thing as the Pet Bar?

**Comment by cdeconinck** [comment]
you mean like the hunter / warlock pet bar ?

**Comment by teelolws** [comment]
Oh I see. Its the timer bar just below your Unit Frame. Paladin Consecration, Mage Water Elemental, a few other spells use the same thing too:
image

**Comment by cdeconinck** [comment]
oh i see, didn't know if was the same bar

**Pull request merged**
